### ISSUE TITLE
Update Home page

### ISSUE THREAD

**Issue by chantzlarge** [chantzlarge/blog#5]
- [x] Add link to About page from Home page

**Comment by 0xlarge** [comment]
As for layout, consider the a16z blog with modifications. The density and whitespace feels serious and with the addition of media, a better typeface and some other minor modifications I believe it'd suit my style well.

[https://future.a16z.com/](https://future.a16z.com/)

**Comment by 0xlarge** [comment]
Updated 'Navbar' partial to address the task mentioned in the original description.

**Comment by 0xlarge** [comment]
Implementation tasks remaining annotated on attached screenshot.
![localhost_1313_ (1)](https://user-images.githubusercontent.com/4284843/123698237-287e1400-d81b-11eb-8bb5-f0ec426792ea.png)

**Comment by chantzlarge** [comment]
- [ ] 'category-list-section' partial 

![category-list-section-partial](https://user-images.githubusercontent.com/4284843/125119946-04d68b80-e0af-11eb-8232-c00447f51462.png)

- [ ] `hero` partial

![hero-partial](https://user-images.githubusercontent.com/4284843/125120055-26377780-e0af-11eb-9aaa-c778c7f9f564.png)

**Comment by chantzlarge** [comment]
![localhost_1313_(iPad Pro)](https://user-images.githubusercontent.com/4284843/125143803-17fe5100-e0d9-11eb-9916-332eadf56733.png)

Latest implementation screenshot...

**Comment by chantzlarge** [comment]
- [ ] Add short bio and profile picture of some kind...

![localhost_1313_(iPad Pro)](https://user-images.githubusercontent.com/4284843/125195226-c6fa7400-e222-11eb-9ec5-33cd5bc92078.png)

**Comment by chantzlarge** [comment]
![Uploading localhost_1313_(iPad Pro) (1).png…]()

Latest implementation...

**Comment by chantzlarge** [comment]
![localhost_1313_(iPad Pro) (1)](https://user-images.githubusercontent.com/4284843/125196103-8270d780-e226-11eb-9e7a-1bb032e92822.png)

Latest implementation...

**Comment by chantzlarge** [comment]
Latest screenshots of iPhone, iPad, and iPad Pro (horizontal)

![localhost_1313_(iPad Pro) (1)](https://user-images.githubusercontent.com/4284843/125330324-d8677d00-e303-11eb-8373-59ab32d2dd91.png)
![localhost_1313_(iPad)](https://user-images.githubusercontent.com/4284843/125330333-db626d80-e303-11eb-951b-f32e69e37999.png)
![localhost_1313_(iPhone 6_7_8)](https://user-images.githubusercontent.com/4284843/125330341-dd2c3100-e303-11eb-886d-400fd5f4bb94.png)

**Comment by chantzlarge** [comment]
![localhost_1313_(iPad Pro) (1)](https://user-images.githubusercontent.com/4284843/125332703-9986f680-e306-11eb-8dce-8e2d871f915e.png)
![localhost_1313_(iPad)](https://user-images.githubusercontent.com/4284843/125332715-9db31400-e306-11eb-9228-5f8686acc433.png)
![localhost_1313_(iPhone 6_7_8)](https://user-images.githubusercontent.com/4284843/125332736-a1df3180-e306-11eb-8ed6-0f0ca1f41277.png)

- [ ] Add "building-with" and "contributing-to" information to short bio on index
- [ ] Add add'l whitespace between "featured article" partial titles and tags
- [ ] Add add'l whitespace between "category list" partial titles and summaries
- [ ] Add projects below "links" partial
- [ ] Add full name to "footer" partial
- [ ] Add social icons to "footer" partial
- [ ] Move copyright statement below name and social icons in "footer" partial
- [ ] Add responsive menu button to "navbar" partial

**Comment by chantzlarge** [comment]
Closing this issue, and reopening more specific issues...
