### ISSUE TITLE
Update About page

### ISSUE THREAD

**Issue by chantzlarge** [chantzlarge/blog#7]

**Comment by 0xlarge** [comment]
The "about" page from Larva Labs is concise and informative while feeling authentic and genuine; I should emulate this style when drafting my own about page:

[https://www.larvalabs.com/about](https://www.larvalabs.com/about)

**Comment by 0xlarge** [comment]
The best format for this would be chronological, so given my 14+ years of software development... what would be the highlights worth exemplifying?

**Comment by chantzlarge** [comment]
Closing issue and reopening once repository is cleaned ;
